
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/nicolascarrillo/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Darwin - 23.2.0 - arm64
